ga4gh/compliance

README.md

When running the example code on my mac I got an error message. Seems to be related to Python3 and the SimpleHTTPServer module being replaced.
Hope it helps others out.

Offer an alternative command line to run the test

---

compliance.html

point at live ensembl site rather than old prototype

update ensembl endpoint

---

.travis.yml
cts-java/pom.xml
docs/UpdatingTheSchemas.md

Create JavaDoc for tests (cts-java module).
Added .travis.yml.
Wrote document describing how to replace the schemas.

Hooked in Travis CI; generate JavaDoc for tests; added schema replacement doc

---

cts-java/src/test/java/org/ga4gh/cts/api/TestData.java
cts-java/src/test/java/org/ga4gh/cts/api/Utils.java
cts-java/src/test/java/org/ga4gh/cts/api/reads/ReadGroupSetsGetByNameIT.java
cts-java/src/test/java/org/ga4gh/cts/api/reads/ReadGroupSetsSearchIT.java
cts-java/src/test/java/org/ga4gh/cts/api/reads/ReadMethodsEndpointAliveIT.java
cts-java/src/test/java/org/ga4gh/cts/api/reads/ReadsSearchIT.java
cts-java/src/test/java/org/ga4gh/cts/api/variants/CallsetsSearchResponseCheckIT.java
cts-java/src/test/java/org/ga4gh/cts/api/variants/VariantSetsSearchIT.java
cts-java/src/test/java/org/ga4gh/cts/api/variants/VariantsGetByIdIT.java
cts-java/src/test/java/org/ga4gh/cts/api/variants/VariantsMethodsEndpointAliveIT.java
cts-java/src/test/java/org/ga4gh/cts/api/variants/VariantsSearchIT.java

Made tests agree with new test data.
Refactored some tests into finer-grained ones.
Removed obsolete ones.

Test cleanup

---

ctk-cli/src/main/resources/application.properties
ctk-server/src/main/resources/application.properties
ctk-testrunner/src/main/resources/application.properties
cts-java/src/test/java/org/ga4gh/cts/api/endpoints/EndpointsTestSuite.java
cts-java/src/test/java/org/ga4gh/cts/api/endpoints/EndpointsTests.java
cts-java/src/test/java/org/ga4gh/cts/api/endpoints/RawEndpointsIT.java
cts-java/src/test/java/org/ga4gh/cts/api/variants/CallsetsSearchResponseCheckIT.java

Moved endpoints-related tests to own package and class.
Fix for #51.

Moved endpoints-related tests to own package and class

---

parent/pom.xml

Changed minimum Maven version to 3.2.5 so it will work with Travis.

Change minimum Maven version to 3.2.5 so it will work with Travis.

---

cts-java/src/test/java/org/ga4gh/cts/api/TestData.java
cts-java/src/test/java/org/ga4gh/cts/api/Utils.java
cts-java/src/test/java/org/ga4gh/cts/api/references/ReferenceBasesSearchIT.java
cts-java/src/test/java/org/ga4gh/cts/api/references/ReferenceSetsSearchIT.java
cts-java/src/test/java/org/ga4gh/cts/api/references/ReferencesSearchIT.java

The references tests are updated to reflect the new data in the compliance dataset.
Also, greater coverage of endpoints, other miscellaneous fixes.
Resolves Issues #69, #54.

Added references tests.

---

cts-java/src/test/java/org/ga4gh/cts/api/Utils.java
cts-java/src/test/java/org/ga4gh/cts/api/datasets/DatasetsPagingIT.java
cts-java/src/test/java/org/ga4gh/cts/api/reads/ReadGroupSetsPagingIT.java
cts-java/src/test/java/org/ga4gh/cts/api/reads/ReadsPagingIT.java
cts-java/src/test/java/org/ga4gh/cts/api/references/ReferenceBasesPagingIT.java
cts-java/src/test/java/org/ga4gh/cts/api/references/ReferenceSetsPagingIT.java
cts-java/src/test/java/org/ga4gh/cts/api/references/ReferencesPagingIT.java
cts-java/src/test/java/org/ga4gh/cts/api/variants/CallSetsPagingIT.java
cts-java/src/test/java/org/ga4gh/cts/api/variants/VariantSetsPagingIT.java

Added paging tests for:
`SearchReadsRequest` / `SearchReadsResponse`
`SearchReadGroupSetsRequest` / `SearchReadGroupSetsResponse`
`SearchDatasetsRequest` / `SearchDatasetsResponse`
`SearchReferenceSetsRequest` / `SearchReferenceSetsResponse`
`SearchReferencesRequest` / `SearchReferencesResponse`
`ListReferenceBasesRequest` / `ListReferenceBasesResponse`
`SearchVariantSetsRequest` / `SearchVariantSetsResponse`
`SearchVariantsRequest` / `SearchVariantsResponse`
`SearchCallSetsRequest` / `SearchCallSetsResponse`

Added paging tests.

---

ctk-testrunner/src/main/java/org/ga4gh/ctk/TestRunner.java
ctk-transport/src/main/java/org/ga4gh/ctk/transport/avrojson/AvroJson.java
cts-java/src/test/java/org/ga4gh/cts/api/variants/CallSetsPagingIT.java
cts-java/src/test/java/org/ga4gh/cts/api/variants/VariantsPagingIT.java

Fix for #81: removed the "stubbing future comms" behavior.
Also removed a misfeature from a few of my early paging tests.

Fix for #81

---

cts-java/src/test/java/org/ga4gh/cts/api/reads/ReadGroupSetsGetByNameIT.java
cts-java/src/test/java/org/ga4gh/cts/api/reads/ReadGroupSetsSearchIT.java
cts-java/src/test/java/org/ga4gh/cts/api/variants/VariantsMethodsEndpointAliveIT.java

Updated tests to expect empty lists instead of exceptions.
(Am also updating the schemas documentation to make this behavior clear and official.)

Fix for #87

---

cts-java/src/test/java/org/ga4gh/cts/core/DatasetIdPropertyIT.java
docs/RunningTests_CLI.md

Moved DatasetIdPropertyIT test to the 'core' package.

Preparation for the big split

---

cts-java/src/test/java/org/ga4gh/cts/api/references/ReferenceBasesPagingIT.java
cts-java/src/test/java/org/ga4gh/cts/api/references/ReferenceSetsPagingIT.java
cts-java/src/test/java/org/ga4gh/cts/api/references/ReferencesPagingIT.java

These changes address @calbach's line comments in the `reference_tests` PR.

Addressed @calbach's line comments

---

cts-java/src/test/java/org/ga4gh/cts/api/references/ReferenceSetsSearchIT.java

Refactored per @jeromekelleher's comments.

Refactored per @jeromekelleher's comments.

---

cts-java/src/test/java/org/ga4gh/cts/api/variants/VariantsMethodsEndpointAliveIT.java

This is pending a decision regarding the correct behavior: 404 error or empty list.
See https://github.com/ga4gh/schemas/issues/471.

Removed test of searchVariants(referenceName = "bogus")

---

ctk-transport/src/main/java/org/ga4gh/ctk/transport/avrojson/AvroJson.java

Fixed #120.
While in that file, I also made the urlRoot instance var private for consistency with the others.

Fix for bug #120.

---

test-data/brca1_HG00096.sam
test-data/brca1_HG00099.sam
test-data/brca1_HG00101.sam

Removed hs37d5 unused reference from SAM files.

---

cts-java/src/test/java/org/ga4gh/cts/api/variants/CallSetsSearchResponseCheckIT.java

Not all VariantSets have CallSets so this test has been changed to check that if a CallSet is returned, it contains reference to the VariantSet it came from. fix #145

Not all VariantSets have CallSets Fix #145

---

cts-java/src/test/java/org/ga4gh/cts/api/variantAnnotation/VariantAnnotationSetsSearchIT.java
cts-java/src/test/java/org/ga4gh/cts/api/variantAnnotation/VariantAnnotationsSearchIT.java

Includes tests on the Analysis record a discussed in #141

update to use additional test data

---

ctk-schemas/src/main/resources/avro/alleleAnnotationmethods.avdl
ctk-schemas/src/main/resources/avro/alleleAnnotations.avdl
cts-java/src/test/java/org/ga4gh/cts/api/variantAnnotation/VariantAnnotationsSearchIT.java

update for schema tweak

---

test-data/OR4F_annotation.vcf

Fixing a typo in the test data.

Test data was failing being read by pyvcf

---

ctk-schemas/src/main/resources/avro/alleleAnnotations.avdl
ctk-schemas/src/main/resources/avro/metadata.avdl
cts-java/src/test/java/org/ga4gh/cts/api/variantAnnotation/VariantAnnotationSetsSearchIT.java
cts-java/src/test/java/org/ga4gh/cts/api/variantAnnotation/VariantAnnotationsSearchIT.java

Updates against schemas/master prepares branch for merge into master.

Remove impact and update datetime

---

ctk-cli/src/main/resources/application.properties
ctk-server/src/main/resources/application.properties
ctk-testrunner/src/main/resources/application.properties
docs/Quickstart.md

The ID scheme in the reference server has changed so the documentation and default datasetId is changed in this PR. @dcolligan @macieksmuga

Update default datasetid

---

cts-java/src/test/java/org/ga4gh/cts/api/reads/ReadsSearchIT.java

Changed expected server response on bad request to 400

---

cts-java/src/test/java/org/ga4gh/cts/api/reads/ReadsSearchIT.java

Test readsSearch with multiple readGroups

---

cts-java/src/test/java/org/ga4gh/cts/api/Utils.java
parent/pom.xml

Remove snapshot, remove incorrect import

---

cts-java/src/test/java/org/ga4gh/cts/api/Utils.java
cts-java/src/test/java/org/ga4gh/cts/api/rnaquantification/ExpressionLevelsIT.java
cts-java/src/test/java/org/ga4gh/cts/api/rnaquantification/RnaQuantificationSearchIT.java
cts-java/src/test/java/org/ga4gh/cts/api/rnaquantification/RnaQuantificationSetsIT.java

This adds a few tests of the RNA functionality including filtering by feature IDs and threshold values. I believe these tests present the minimum level of request and response functionality.
A few more tests could be added that show that responses are well formed and contain values expected from the test data. @dcolligan @saupchurch

RNA Expression Level Tests

---

ctk-server/pom.xml
parent/pom.xml

This PR changes the POM to point at the proper schemas. @kozbo

Point at master

---

test-data/cgd/cgd-test.ttl

* bug fix:   update test-data/cgd-test.ttl to the latest from server/tests/data

update g2p test data
