ga4gh/compliance

.travis.yml
ctk-domain/src/main/assertj-assertions/org/ga4gh/methods/SearchVariantsRequestAssert.java
ctk-schemas/src/main/resources/avro/variantmethods.avdl
ctk-testrunner/pom.xml
ctk-testrunner/src/main/java/org/ga4gh/ctk/AntExecutor.java
ctk-transport/src/main/java/org/ga4gh/ctk/transport/avrojson/AvroJson.java
ctk-transport/src/main/java/org/ga4gh/ctk/transport/protocols/Client.java
ctk-transport/src/test/java/org/ga4gh/ctk/transport/avrojson/JsonMakerTest.java
cts-java/pom.xml
cts-java/src/test/java/org/ga4gh/cts/api/DatasetIdPropertyIT.java
cts-java/src/test/java/org/ga4gh/cts/api/TestData.java
cts-java/src/test/java/org/ga4gh/cts/api/datasets/DatasetsSearchIT.java
cts-java/src/test/java/org/ga4gh/cts/api/reads/ReadGroupSetsGetByIdIT.java
cts-java/src/test/java/org/ga4gh/cts/api/reads/ReadGroupSetsSearchIT.java
cts-java/src/test/java/org/ga4gh/cts/api/reads/ReadGroupsGetByIdIT.java
cts-java/src/test/java/org/ga4gh/cts/api/reads/ReadsSearchIT.java
cts-java/src/test/java/org/ga4gh/cts/api/variants/CallsetsSearchResponseCheckIT.java
cts-java/src/test/java/org/ga4gh/cts/api/variants/VariantSetsSearchIT.java
cts-java/src/test/java/org/ga4gh/cts/api/variants/VariantsGetByIdIT.java
cts-java/src/test/java/org/ga4gh/cts/api/variants/VariantsSearchIT.java
docs/README.md
docs/RunningTests_CLI.md
docs/WritingATest.md
parent/pom.xml

- Fix to Maven build problems (I hope).  If you tried to build before, you should clean out the JARs you built before from your local Maven cache:
```
$ rm -r ~/.m2/repository/org/ga4gh
```
- You can now supply a dataset ID to override the default standard compliance test data:
Supply `-Dcfg.tgt.dataset_id="name"` to the `java` program:
```
$ java -Dcfg.tgt.dataset_id="my compliance data"` org.ga4gh....
```
Or supply `--cfg.tgt.dataset_id="name"` to the `ctk` shell script:
```
$ ctk --cfg.tgt.dataset_id="my compliance data" ...
```
Plus:
Lots of doc fixes.
Some new tests.
One bug fix (sorry, no issue ID).

Possible Maven build fix; doc updates; new tests; bug fixed

---

ctk-cli/src/main/resources/application.properties
ctk-cli/src/main/resources/ctk
ctk-server/pom.xml
ctk-server/src/main/resources/application.properties
ctk-server/src/main/resources/ctk
ctk-testrunner/src/main/resources/application.properties
ctk-transport/src/main/java/org/ga4gh/ctk/transport/URLMAPPING.java
ctk-transport/src/main/java/org/ga4gh/ctk/transport/avrojson/AvroJson.java
ctk-transport/src/main/resources/defaulttransport.properties
ctk-transport/src/test/java/org/ga4gh/ctk/transport/URLMAPPINGTest.java
cts-java/src/main/resources/defaulttransport.properties
docs/ConfigTheCTK.md
docs/README-IntroAtCommandLine.txt
docs/RunningTests_CLI.md
docs/RunningTests_maven.md
docs/WritingATest.md
parent/pom.xml

The ref server just dropped version numbers from its URLs, and it see…ms that that's not the custom with other GA4GH servers.  I edited docs and config files to drop the `/v0.5.1` suffixes from default and example URLs.

Remove version numbers from example and default URLs

---

ctk-transport/src/main/java/com/shopobot/util/FragmentEncoder.java
ctk-transport/src/main/java/com/shopobot/util/URL.java
ctk-transport/src/main/java/org/ga4gh/ctk/transport/avrojson/AvroJson.java
ctk-transport/src/test/java/com/shopobot/util/URLTest.java

Assemble URLs more carefully so as to preserve any query string the base URL might contain. Fix for #42.
Used com.shopobot.util.URL, a very handy object-oriented URL manipulator.

Fix for #42.

---

ctk-transport/src/main/java/org/ga4gh/ctk/transport/FragmentEncoder.java
ctk-transport/src/main/java/org/ga4gh/ctk/transport/TransportUtils.java
ctk-transport/src/main/java/org/ga4gh/ctk/transport/URL.java
ctk-transport/src/main/java/org/ga4gh/ctk/transport/avrojson/AvroJson.java
ctk-transport/src/test/java/org/ga4gh/ctk/transport/URLTest.java
cts-java/src/test/java/org/ga4gh/cts/api/variants/CallsetsSearchResponseCheckIT.java

Fixed a packaging problem that prevented this fix from running under the `ctk` shell script.
Also fixed `CallsetsSearchResponseCheckIT` to construct URLs correctly.

Fixed problems merging server base URL with endpoints when the base contains a query string

---

parent/pom.xml

Make Maven enforce minimum Maven version (3.3.3) and Java version (JDK 1.8)

---

ctk-cli/pom.xml
ctk-server/pom.xml
ctk-testrunner/pom.xml
ctk-transport/pom.xml
parent/pom.xml

Fix for #32: got rid of unused Jackson dependencies.  Note that Spring uses some other pieces of Jackson.
Also made the two Enforcer messages more helpful.

Remove unused Jackson dependencies, produce more helpful Enforcer messages

---

ctk-transport/src/main/java/org/ga4gh/ctk/transport/URLMAPPINGImpl.java
ctk-transport/src/main/java/org/ga4gh/ctk/transport/avrojson/AvroJson.java
ctk-transport/src/main/resources/defaulttransport.properties
ctk-transport/src/test/java/org/ga4gh/ctk/transport/URLTest.java
cts-java/src/main/resources/defaulttransport.properties

Fixed #42: Found and eliminated code that was appending a slash to the urlRoot when run under the `ctk` script.  This time for sure!
Created unit tests for makeUrl and friends.
Removed unnecessary "/" prefixes from some predefined endpoint paths.

Fixed #42: Found and eliminated code that was appending a slash to the urlRoot when run under the `ctk` script

---

ctk-cli/src/main/resources/application.properties
ctk-cli/src/main/resources/ctk
ctk-server/src/main/java/org/ga4gh/ctk/server/ServerTestController.java
ctk-server/src/main/resources/application.properties
ctk-server/src/main/resources/ctk
ctk-testrunner/src/main/java/org/ga4gh/ctk/AntExecutor.java
ctk-testrunner/src/main/java/org/ga4gh/ctk/TestRunner.java
ctk-testrunner/src/main/java/org/ga4gh/ctk/config/Props.java
ctk-testrunner/src/main/resources/application.properties
ctk-transport/src/main/java/org/ga4gh/ctk/transport/URLMAPPINGImpl.java
cts-java/src/test/java/org/ga4gh/cts/api/DatasetIdPropertyIT.java
cts-java/src/test/java/org/ga4gh/cts/api/TestData.java
docs/README-IntroAtCommandLine.txt
docs/RunningTests_CLI.md
docs/RunningTests_maven.md

Fix for #49.
We now allow setting the dataset ID via command line, environment variable, or Java System property.  Note that the new dataset ID property name is `ctk.tgt.dataset_id` (formerly `cfg.tgt.dataset_id`).  Examples:
```bash
$ ./ctk --ctk.tgt.dataset_id=my_dataset_id
```
or
```bash
$ env CTK_TGT_DATASET_ID=my_dataset ./ctk
```
or
```bash
$ java -Dctk.tgt.dataset_id=my_dataset_id -jar ctk-cli-0.5.1-SNAPSHOT.jar
```
etc.

Compliance redux

---

cts-java/pom.xml
docs/RunningTests_maven.md
parent/pom.xml

You can now skip running the server tests when you build, saving time when doing frequent edits and compilation.
```bash
$ mvn -Dcts.skipITs=true clean install
```
The `install` phase will default to running the server tests, just as things worked before this change.

Skip running the server tests when you build

---

ctk-transport/src/main/java/org/ga4gh/ctk/transport/GAWrapperException.java
ctk-transport/src/main/java/org/ga4gh/ctk/transport/RespCode.java
ctk-transport/src/main/java/org/ga4gh/ctk/transport/avrojson/AvroJson.java
ctk-transport/src/main/java/org/ga4gh/ctk/transport/protocols/Client.java
cts-java/src/test/java/org/ga4gh/cts/api/TestData.java
cts-java/src/test/java/org/ga4gh/cts/api/Utils.java
cts-java/src/test/java/org/ga4gh/cts/api/datasets/DatasetsSearchIT.java
cts-java/src/test/java/org/ga4gh/cts/api/reads/ReadGroupSetsGetByIdIT.java
cts-java/src/test/java/org/ga4gh/cts/api/reads/ReadGroupSetsSearchIT.java
cts-java/src/test/java/org/ga4gh/cts/api/reads/ReadGroupsGetByIdIT.java
cts-java/src/test/java/org/ga4gh/cts/api/reads/ReadMethodsEndpointAliveIT.java
cts-java/src/test/java/org/ga4gh/cts/api/reads/ReadsSearchIT.java
cts-java/src/test/java/org/ga4gh/cts/api/references/ReferenceBasesSearchIT.java
cts-java/src/test/java/org/ga4gh/cts/api/references/ReferenceSetsSearchIT.java
cts-java/src/test/java/org/ga4gh/cts/api/references/ReferencesSearchIT.java
cts-java/src/test/java/org/ga4gh/cts/api/variants/CallsetsSearchResponseCheckIT.java
cts-java/src/test/java/org/ga4gh/cts/api/variants/VariantSetsSearchIT.java
cts-java/src/test/java/org/ga4gh/cts/api/variants/VariantsGetByIdIT.java
cts-java/src/test/java/org/ga4gh/cts/api/variants/VariantsSearchIT.java
test-data/convert_to_binary.sh

Prior to this PR, tests needed to use a special `WireTracker` object to monitor a request and check if it generated an exception.
This change makes it so that server requests can now throw `GAException`, just as you'd expect.
You can capture the thrown exception and test the `errorCode`, message, etc.
In addition, you can get the request's HTTP status code from the exception object.  Many tests need to test this value.

GAException support

---

cts-java/src/test/java/org/ga4gh/cts/api/datasets/DatasetsSearchIT.java

Fix for #70.  The test no longer assumes the compliance dataset is the first one returned.

Fix for #70

---

cts-java/src/test/java/org/ga4gh/cts/api/TestData.java
cts-java/src/test/java/org/ga4gh/cts/api/Utils.java
cts-java/src/test/java/org/ga4gh/cts/api/reads/ReadsSearchIT.java
cts-java/src/test/java/org/ga4gh/cts/api/variants/CallSetsPagingIT.java
cts-java/src/test/java/org/ga4gh/cts/api/variants/CallsetsSearchResponseCheckIT.java
cts-java/src/test/java/org/ga4gh/cts/api/variants/VariantsPagingIT.java

I added `CallSet` paging tests and fixed the `ReadGroup` and `ReadGroupSet` names in class `TestData`.

CallSets paging tests; fixed ReadGroup and ReadGroupSet names

---

cts-java/src/test/java/org/ga4gh/cts/api/TestData.java

This field has type `{null, int}` in the [schema](https://github.com/ga4gh/schemas/blob/master/src/main/resources/avro/references.avdl#L69).

Change expected refset taxon ID from string -> int

---

cts-java/src/test/java/org/ga4gh/cts/api/TestData.java

This is computed as `MD5("90977a37195d3fd247e4916b5b4cbae8")` per the [documentation](https://github.com/ga4gh/schemas/blob/master/src/main/resources/avro/references.avdl#L89).

Fix the test data reference set checksum

---

cts-java/src/test/java/org/ga4gh/cts/api/Utils.java
cts-java/src/test/java/org/ga4gh/cts/api/datasets/DatasetsPagingIT.java
cts-java/src/test/java/org/ga4gh/cts/core/CatchExceptionsIT.java
cts-java/src/test/java/org/ga4gh/cts/core/DatasetIdPropertyIT.java

`Utils.catchGAWrapperException` now calls `fail()` when the enclosed code doesn't throw `GAWrapperException`.

Fix for #85: added logging to Utils.catchGAWrapperException

---

ctk-transport/src/main/java/org/ga4gh/ctk/transport/URLMAPPING.java
cts-java/src/test/java/org/ga4gh/cts/api/endpoints/RawEndpointsIT.java

Now this only tests what happens when you POST a bad payload to a search endpoint.
Also added a couple of missing search endpoints.

Fix for #88.

---

docs/ArchitectureOverview.md
docs/ConfigTheCTK.md
docs/Quickstart.md
docs/StructureAndRationale.md

Fixed smartquotes in code blocks in Quickstart.md
Added unzip to quickstart requirements to Quickstart.md
Fixed unmatched curly brace in Parameters annotation in ArchitectureOverview.md
Fixed a number of paths and clarified which .properties need editing in ConfigTheCTK.md
extra hyphen in 'cts-demo-java' in StructureAndRationale.md

Some documentation fixes (squashed)

---

test-data/convert_to_binary.sh

Fixes issue #131. Also added a short preamble indicating that this script is for illustrative purposes only.

Filename in convert_to_binary.sh is now correct.

---

cts-java/src/test/java/org/ga4gh/cts/api/references/ReferencesSearchIT.java

Fixed issue #133 : Compared returned reference accessions against single element array as opposed to string.

fixed #133

---

cts-java/src/test/java/org/ga4gh/cts/api/Utils.java
cts-java/src/test/java/org/ga4gh/cts/api/reads/ReadGroupSetsPagingIT.java
cts-java/src/test/java/org/ga4gh/cts/api/reads/ReadsSearchIT.java

Fix #117 by reproducing Herb's changes on PR #128. Sets the checksum for a SearchReferenceRequest, removes unecessary calls to getReferenceId, and tests to ensure the length of the reference set arrays are equal to 1.

Remove unecessary getReferenceId calls and check that reference set lists are length 1

---

ctk-cli/pom.xml
ctk-cli/src/main/resources/application.properties
ctk-cli/src/main/resources/ctk
ctk-domain/pom.xml
ctk-schemas/pom.xml
ctk-server/pom.xml
ctk-server/src/main/resources/application.properties
ctk-server/src/main/resources/ctk
ctk-testrunner/pom.xml
ctk-testrunner/src/main/resources/application.properties
ctk-transport/pom.xml
cts-demo-java/pom.xml
cts-java/pom.xml
dist/pom.xml
docs/ConfigTheCTK.md
docs/README-Server.txt
docs/RunningTests_CLI.md
docs/RunningTests_maven.md
parent/pom.xml
pom.xml

I should have caught this one before. The compliance suite was using the `0.5.1-SNAPSHOT` name internally all over the place. Please take a quick look and +1 so we can release this ASAP.

Changed internal version from 0.5.1-SNAPSHOT to 0.6.0a1

---

cts-java/src/test/java/org/ga4gh/cts/api/variants/CallSetsSearchResponseCheckIT.java

Each CallSet contains a list of VariantSets. This test makes sure that VariantSets are found for each variantSetId in a CallSet record. fix #146

New test for finding Variant Sets related to a Call Set fix #146

---

cts-java/src/test/java/org/ga4gh/cts/api/reads/ReadsSearchIT.java

Changed the test to match the title, no reads should be found in the range. We need to edit the range values to find a true empty range.

Fix broken test searchReadsWithUninterestingRangeProducesZeroReads

---

ctk-schemas/src/main/resources/avro/alleleAnnotationmethods.avdl
ctk-schemas/src/main/resources/avro/metadata.avdl

Hi @david4096
This updates the compliance schemas to those used by the schema & server repos.
I'm sending it as a PR so you can see the changes and merge when convenient. The main difference is the metadata fix, which should not have any impact on the tests.
In addition, SearchVariantAnnotationsRequest has had feature_ids renamed to featureIds to match the standard naming convention. The reference server and ensembl server have been updated for this change, so the compliance test filtering on feature id will fail until this PR is merged.

sync schemas - use approved metadata records & correct feature search key

---

ctk-domain/pom.xml

When switching back and forth from branches with different schema the list of assertion files to generate wasn't being deleted. Now it is, so you can `mvn clean` between schema changes without an issue.

Changed ctk-domain pom.xml to delete generated assertions fix #152

---

cts-java/src/test/java/org/ga4gh/cts/api/variantAnnotation/VariantAnnotationSetsSearchIT.java

Ref server is currently failing this test without the GET endpoint implemented.

Added a test for finding variant annotation sets by their ID. fixed #144

---

cts-java/src/test/java/org/ga4gh/cts/api/variantAnnotation/VariantAnnotationsSearchIT.java
cts-java/src/test/java/org/ga4gh/cts/api/variants/VariantSetsSearchIT.java

This requires a second VariantSet, so VariantSetsSearchIT is also updated - it is a more useful check to page through more than one record.

Check that Variant in the VariantAnnotation record exists 

---

ctk-schemas/src/main/resources/avro/genotypephenotype.avdl
ctk-schemas/src/main/resources/avro/genotypephenotypemethods.avdl
ctk-schemas/src/main/resources/avro/metadata.avdl
ctk-schemas/src/main/resources/avro/references.avdl
ctk-schemas/src/main/resources/avro/sequenceAnnotations.avdl
ctk-transport/src/main/java/org/ga4gh/ctk/transport/URLMAPPING.java
ctk-transport/src/main/java/org/ga4gh/ctk/transport/URLMAPPINGImpl.java
ctk-transport/src/main/java/org/ga4gh/ctk/transport/protocols/Client.java
cts-java/src/test/java/org/ga4gh/cts/api/TestData.java
cts-java/src/test/java/org/ga4gh/cts/api/g2p/GenotypePhenotypeSearchIT.java
cts-java/src/test/java/org/ga4gh/cts/api/g2p/GenotypePhenotypeTestSuite.java
cts-java/src/test/java/org/ga4gh/cts/api/g2p/GenotypePhenotypeTests.java
cts-java/src/test/java/org/ga4gh/cts/api/g2p/package-info.java
test-data/cgd-test.ttl

Plucked the g2p changes into the latest compliance suite here and refactored ontology `name` to `term` where needed.
FWIW I was able to get 11/12 tests to pass based on https://github.com/ga4gh/server/pull/933
@bwalsh I believe you can close out your other pull request this will be the new starting point.
```
simpleEvidenceSearchExternalIdentifier	Failure	expected:<"[early] trials"> but was:<"[late] trials">
```

Brings g2p in with latest schemas and add test data file

---

ctk-cli/pom.xml
ctk-cli/src/main/resources/application.properties
ctk-cli/src/main/resources/ctk
ctk-domain/pom.xml
ctk-schemas/pom.xml
ctk-server/pom.xml
ctk-server/src/main/resources/application.properties
ctk-server/src/main/resources/ctk
ctk-testrunner/pom.xml
ctk-testrunner/src/main/resources/application.properties
ctk-transport/pom.xml
cts-demo-java/pom.xml
cts-java/pom.xml
dist/pom.xml
docs/ConfigTheCTK.md
docs/README-Server.txt
docs/RunningTests_maven.md
parent/pom.xml
pom.xml

With the latest server/master we have removed padding from identifiers. This fix brings the version number in line with schemas and removes `=` from datasetId.

Version bump, point to dataset

---

cts-java/src/test/java/org/ga4gh/cts/api/sequenceAnnotations/FeaturesSearchIT.java

fixed incorrect return count in `FeatuesSearchIT` method `checkFeaturesSearchByParentId` from 20 to 50.

Fixed typo in FeatureSearchIT test

---

cts-java/src/test/java/org/ga4gh/cts/api/rnaquantification/RnaQuantificationSearchIT.java

@saupchurch is there really only supposed to be 1 rnaQuantification loaded into the server in the current test_data dataset?

Fix checkExpectedNumberOfRnaQuantifications

---

ctk-transport/src/main/java/org/ga4gh/ctk/transport/URLMAPPINGImpl.java
cts-java/src/test/java/org/ga4gh/cts/api/rnaquantification/ExpressionLevelsIT.java

Fixes a capitalization bug in the callsets endpoint and adds a test ensuring that features exist for expression level objects. @dcolligan @saupchurch

RNA Update

---

ctk-transport/src/main/java/org/ga4gh/ctk/transport/URLMAPPINGImpl.java
ctk-transport/src/main/java/org/ga4gh/ctk/transport/protocols/Client.java
ctk-transport/src/main/resources/defaulttransport.properties
cts-java/pom.xml
cts-java/src/main/resources/defaulttransport.properties
cts-java/src/test/java/org/ga4gh/cts/api/references/ReferenceBasesPagingIT.java
cts-java/src/test/java/org/ga4gh/cts/api/references/ReferenceBasesSearchIT.java

This PR changes the functionality of the list reference bases endpoint to a style more consistent with the remainder of the API. https://github.com/ga4gh/schemas/pull/647 https://github.com/ga4gh/server/pull/1309
* Reference ID's are now included directly in the request.
* The path for listing reference bases is simpler.
If the schemas are accepted the POM's need to be changed before this PR is merged.

Change list reference bases from GET to POST

---

ctk-cli/pom.xml
ctk-cli/src/main/resources/application.properties
ctk-cli/src/main/resources/ctk
ctk-domain/pom.xml
ctk-server/pom.xml
ctk-server/src/main/resources/application.properties
ctk-server/src/main/resources/ctk
ctk-testrunner/pom.xml
ctk-testrunner/src/main/resources/application.properties
ctk-transport/pom.xml
cts-demo-java/pom.xml
cts-java/pom.xml
dist/pom.xml
docs/ConfigTheCTK.md
docs/README-Server.txt
docs/RunningTests_maven.md
docs/UpdatingTheSchemas.md
parent/pom.xml
pom.xml
test-data/rna_control_file.tsv

The important hand edited properties are now editable in one place (parent/pom.xml).
The schema version was being set in multiple places. Added a brief comment that explains how to switch to your own repo for schemas. Place the versioning in a single property so it is reused throughout.
Add docs for usage
Pushes version to 0.6.0a7 and adds version as property of parent/pom.xml.
@bwalsh

Unify properties for jitpack and version

---

cts-java/src/test/java/org/ga4gh/cts/api/endpoints/RawEndpointsIT.java

A change in the server made it so empty request bodies could be accepted. @ejacox

Accept blank string
